---
# Ansible playbook SonarQube container setup

- name: docker pull sonarqube
  shell: docker pull sonarqube:8-community

- name: Up a container with the image
  shell: docker run -d \
    --name sonarqube \
    --ulimit nofile=65536:65536 \
    -e SONAR_JDBC_URL=jdbc:postgresql://postgres:5432/sonarqube \
    -e SONAR_JDBC_USERNAME=postgres \
    -e SONAR_JDBC_PASSWORD=mysecretpassword \
    -v sonarqube_data:/opt/sonarqube/data \
    -v sonarqube_extensions:/opt/sonarqube/extensions \
    -v sonarqube_logs:/opt/sonarqube/logs \
    -p 9000:9000 sonarqube:8-community

- name: Connected the container to the network
  shell: docker network connect taskNetwork sonarqube
