---
# Ansible playbook SonarQube container setup

- name: Create a container with the image
  community.general.docker_container:
    name: sonarqube
    image: sonarqube:8-community
    container_default_behavior: compatibility
    ulimits:
      - nofile:65536:65536
    networks:
      - name: "taskNetwork"
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    env:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: "postgres"
      SONAR_JDBC_PASSWORD: "mysecretpassword"
    healthcheck:
      # Check if nginx server is healthy by curl'ing the server.
      # If this fails or timeouts, the healthcheck fails.
      test: ["CMD", "curl", "--fail", "http://http://15.185.223.198:9000/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s